version: "2"

run:
  tests: false

linters:
  default: all
  disable:
    - wsl
    - lll
    - funlen
    - godox
    - mnd
    - gocognit
    - err113
    - gochecknoglobals
    - nlreturn
    - wrapcheck
    - cyclop
    - depguard
    - exhaustruct
    - wsl_v5
    - varnamelen
    - godoclint
    - noinlineerr
    - inamedparam
    - intrange
    - ireturn
    - maintidx
    - gosec
  exclusions:
    paths:
      - hack
      - proxies

