version: "2"

run:
  tests: false
  skip-dirs:
    - hack
    - proxies

linters:
  default: all
  disable:
    - wsl
    - lll
    - funlen
    - godox
    - mnd
    - gocognit
    - err113
    - gochecknoglobals
    - nlreturn
    - wrapcheck

