project_name: mittens
env:
- CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
- main: ./cmd/kubectl-mittens/
  binary: kubectl-mittens
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
    - goos: darwin
      goarch: arm64
    - goos: darwin
      goarch: arm
    - goos: windows
      goarch: 386
    - goos: windows
      goarch: arm64
    - goos: windows
      goarch: arm
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'mittens_checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^scripts:'
    - '^proxies:'
