version: 2

project_name: mittens
env:
- CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
- main: ./cmd/kubectl-mittens/
  binary: kubectl-mittens
  goos:
    - linux
  goarch:
    - amd64
    - arm64
archives:
- name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
checksum:
  name_template: 'mittens_checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^scripts:'
    - '^proxies:'
